--- 
abstract: Nested buffers for templating systems
author: 
  - Alex Vandiver <alexmv@bestpractical.com>
distribution_type: module
generated_by: Module::Install version 0.68
license: Artistic
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: String-BufferStack
no_index: 
  directory: 
    - inc
    - t
version: 1.02
